### PR TITLE
Updated Spanish translations

### PR DESCRIPTION
**Pull request by moshpirit**

### CODE REVIEW

**Comment by tslocum** [comment]
Thank you for your efforts.  Unfortunately, if I accept your translations via pull request, the next time I export translations from Get Localization, they would be overwritten.  I should have mentioned this in the README initially, and have updated it now to clarify.

This page displays all of your changed text: https://github.com/moshpirit/MeditationAssistant/commit/9fd099105e1c5e8726592377d5c6f613441a73ec

Could you please implement your changes here: https://www.getlocalization.com/meditationassistant/

**Comment by moshpirit** [comment]
OK, I've just finished the translations (hard work doing it twice, but it's done):

100% translated, but shows this message: "Please vote or suggest new translations" should I be named proofreader as I'm in another projects such AndStatus, Xabber and Mirakel? I don't know how to vote the translations (I'm used to use pull requests, Crowdin and Weblate)

**Comment by tslocum** [comment]
Thanks again for submitting twice.  I don't think you should worry about voting on translations, I believe that comes into play when there are multiple people working on the same strings.

**Comment by moshpirit** [comment]
OK, good! ;-)

**Pull request closed without merging**
